import { http, createConfig } from "wagmi";
import { acala, ancient8, ancient8Sepolia, anvil, apexTestnet, arbitrum, arbitrumGoerli, arbitrumNova, arbitrumSepolia, areonNetwork, areonNetworkTestnet, artelaTestnet, astar, astarZkEVM, astarZkyoto, aurora, auroraTestnet, auroria, avalanche, avalancheFuji, bahamut, base, baseGoerli, baseSepolia, beam, beamTestnet, bearNetworkChainMainnet, bearNetworkChainTestnet, berachainTestnet, berachainTestnetbArtio, bevmMainnet, bitkub, bitkubTestnet, bitTorrent, bitTorrentTestnet, blast, blastSepolia, bob, boba, bronos, bronosTestnet, bsc, bscGreenfield, bscTestnet, btr, btrTestnet, bxn, bxnTestnet, canto, celo, celoAlfajores, chiliz, classic, confluxESpace, confluxESpaceTestnet, coreDao, crab, cronos, cronosTestnet, crossbell, cyber, cyberTestnet, darwinia, dchain, dchainTestnet, defichainEvm, defichainEvmTestnet, degen, dfk, dodochainTestnet, dogechain, dreyerxMainnet, edgeless, edgelessTestnet, edgeware, edgewareTestnet, ekta, ektaTestnet, eon, eos, eosTestnet, etherlink, etherlinkTestnet, evmos, evmosTestnet, fantom, fantomSonicTestnet, fantomTestnet, fibo, filecoin, filecoinCalibration, filecoinHyperspace, flare, flareTestnet, flowMainnet, flowPreviewnet, flowTestnet, foundry, fraxtal, fraxtalTestnet, funkiSepolia, fuse, fuseSparknet, gnosis, gnosisChiado, gobi, goerli, ham, haqqMainnet, haqqTestedge2, hardhat, harmonyOne, hedera, hederaPreviewnet, hederaTestnet, holesky, immutableZkEvm, immutableZkEvmTestnet, inEVM, iotexTestnet, jbc, jbcTestnet, kakarotSepolia, karura, kava, kavaTestnet, kcc, klaytn, klaytnBaobab, koi, kroma, kromaSepolia, l3x, l3xTestnet, lightlinkPegasus, lightlinkPhoenix, linea, lineaGoerli, lineaSepolia, lineaTestnet, lisk, liskSepolia, localhost, lukso, luksoTestnet, lycan, lyra, mainnet, mandala, manta, mantaSepoliaTestnet, mantaTestnet, mantle, mantleSepoliaTestnet, mantleTestnet, merlin, metachain, metachainIstanbul, metalL2, meter, meterTestnet, metis, metisGoerli, mev, mevTestnet, mintSepoliaTestnet, mode, modeTestnet, moonbaseAlpha, moonbeam, moonbeamDev, moonriver, morphHolesky, morphSepolia, nautilus, neonDevnet, neonMainnet, nexi, nexilix, oasisTestnet, oasys, okc, oortMainnetDev, opBNB, opBNBTestnet, optimism, optimismGoerli, optimismSepolia, otimDevnet, palm, palmTestnet, pgn, pgnTestnet, phoenix, playfiAlbireo, plinga, plumeTestnet, polygon, polygonAmoy, polygonMumbai, polygonZkEvm, polygonZkEvmCardona, polygonZkEvmTestnet, pulsechain, pulsechainV4, qMainnet, qTestnet, real, redbellyTestnet, redstone, reyaNetwork, rollux, rolluxTestnet, ronin, rootstock, rootstockTestnet, rss3, rss3Sepolia, saigon, sapphire, sapphireTestnet, satoshiVM, satoshiVMTestnet, scrollSepolia, sei, seiDevnet, seiTestnet, sepolia, shardeumSphinx, shibarium, shibariumTestnet, shimmer, shimmerTestnet, skaleBlockBrawlers, skaleCalypso, skaleCalypsoTestnet, skaleCryptoBlades, skaleCryptoColosseum, skaleEuropa, skaleEuropaTestnet, skaleExorde, skaleHumanProtocol, skaleNebula, skaleNebulaTestnet, skaleRazor, skaleTitan, skaleTitanTestnet, songbird, songbirdTestnet, spicy, stratis, syscoin, syscoinTestnet, taiko, taikoHekla, taikoJolnir, taikoKatla, taikoTestnetSepolia, taraxa, taraxaTestnet, telcoinTestnet, telos, telosTestnet, tenet, thaiChain, thunderTestnet, unreal, vechain, wanchain, wanchainTestnet, wemix, wemixTestnet, x1Testnet, xai, xaiTestnet, xdc, xdcTestnet, xLayer, xLayerTestnet, xrSepolia, yooldoVerse, yooldoVerseTestnet, zetachain, zetachainAthensTestnet, zhejiang, zilliqa, zilliqaTestnet, zircuitTestnet, zkFair, zkFairTestnet, zkLinkNova, zkLinkNovaSepoliaTestnet, zkSync, zkSyncInMemoryNode, zkSyncLocalNode, zkSyncSepoliaTestnet, zkSyncTestnet, zora, zoraSepolia, zoraTestnet } from "wagmi/chains";
import { coinbaseWallet, injected, metaMask } from "wagmi/connectors";
import { iotex } from "./iotex";

export const config = createConfig({
    chains: [acala, ancient8, ancient8Sepolia, anvil, apexTestnet, arbitrum, arbitrumGoerli, arbitrumNova,
        astar, astarZkEVM, astarZkyoto, arbitrumSepolia, areonNetwork, areonNetworkTestnet,
        artelaTestnet, aurora, auroraTestnet, auroria, avalanche, avalancheFuji, bahamut,
        base, baseGoerli, baseSepolia, beam, beamTestnet, bearNetworkChainMainnet, bearNetworkChainTestnet,
        berachainTestnet, berachainTestnetbArtio, bevmMainnet, bitkub, bitkubTestnet, bitTorrent,
        bitTorrentTestnet, blast, blastSepolia, bob, boba, bronos, bronosTestnet, bsc, bscTestnet,
        bscGreenfield, btr, btrTestnet, bxn, bxnTestnet, canto, celo, celoAlfajores, chiliz, classic,
        confluxESpace, confluxESpaceTestnet, coreDao, crab, cronos, cronosTestnet, crossbell, cyber,
        cyberTestnet, darwinia, dchain, dchainTestnet, defichainEvm, defichainEvmTestnet, degen, dfk,
        dodochainTestnet, dogechain, dreyerxMainnet, edgeless, edgelessTestnet, edgeware, edgewareTestnet,
        eon, eos, eosTestnet, etherlink, etherlinkTestnet, evmos, evmosTestnet, ekta, ektaTestnet,
        fantom, fantomSonicTestnet, fantomTestnet, fibo, filecoin, filecoinCalibration, filecoinHyperspace,
        flare, flareTestnet, flowPreviewnet, flowMainnet, flowTestnet, fraxtal, fraxtalTestnet,
        funkiSepolia, fuse, fuseSparknet, iotex, iotexTestnet, jbc, jbcTestnet, karura, gobi, goerli,
        gnosis, gnosisChiado, ham, harmonyOne, haqqMainnet, haqqTestedge2, hedera, hederaTestnet,
        hederaPreviewnet, holesky, immutableZkEvm, immutableZkEvmTestnet, inEVM, kakarotSepolia, kava,
        kavaTestnet, kcc, klaytn, klaytnBaobab, koi, kroma, kromaSepolia, l3x, l3xTestnet, lightlinkPegasus,
        lightlinkPhoenix, linea, lineaGoerli, lineaSepolia, lineaTestnet, lisk, liskSepolia, localhost,
        lukso, luksoTestnet, lycan, lyra, mainnet, mandala, manta, mantaSepoliaTestnet, mantaTestnet,
        mantle, mantleSepoliaTestnet, mantleTestnet, merlin, metachain, metachainIstanbul, metalL2,
        meter, meterTestnet, metis, metisGoerli, mev, mevTestnet, mintSepoliaTestnet, mode, modeTestnet,
        moonbaseAlpha, moonbeam, moonbeamDev, moonriver, morphHolesky, morphSepolia, nautilus, neonDevnet,
        neonMainnet, nexi, nexilix, oasys, oasisTestnet, okc, optimism, optimismGoerli, optimismSepolia,
        opBNB, opBNBTestnet, oortMainnetDev, otimDevnet, palm, palmTestnet, playfiAlbireo, pgn, pgnTestnet,
        phoenix, plinga, plumeTestnet, polygon, polygonAmoy, polygonMumbai, polygonZkEvm, polygonZkEvmCardona,
        polygonZkEvmTestnet, pulsechain, pulsechainV4, qMainnet, qTestnet, real, redbellyTestnet, redstone,
        reyaNetwork, rollux, rolluxTestnet, ronin, rootstock, rootstockTestnet, rss3, rss3Sepolia,
        sapphire, sapphireTestnet, satoshiVM, satoshiVMTestnet,  scrollSepolia, sei, seiDevnet,
        seiTestnet, sepolia, shimmer, shimmerTestnet, skaleBlockBrawlers, skaleCalypso, skaleCalypsoTestnet,
        skaleCryptoBlades, skaleCryptoColosseum, skaleEuropa, skaleEuropaTestnet, skaleExorde, skaleHumanProtocol,
        skaleNebula, skaleNebulaTestnet, skaleRazor, skaleTitan, skaleTitanTestnet, songbird, songbirdTestnet,
        spicy, shardeumSphinx, shibarium, shibariumTestnet, stratis, syscoin, syscoinTestnet, taraxa,
        taiko, taikoHekla, taikoJolnir, taikoKatla, taikoTestnetSepolia, taraxaTestnet, telcoinTestnet,
        telos, telosTestnet, tenet, thaiChain, thunderTestnet, unreal, vechain, wanchain, wanchainTestnet,
        wemix, wemixTestnet, xLayerTestnet, xLayer, xai, xaiTestnet, xdc, xdcTestnet, xrSepolia,
        yooldoVerse, yooldoVerseTestnet, zetachain, zetachainAthensTestnet, zhejiang, zilliqa, zilliqaTestnet,
        zkFair, zkFairTestnet, zkLinkNova, zkLinkNovaSepoliaTestnet, zkSync, zkSyncInMemoryNode, zkSyncLocalNode,
        zkSyncSepoliaTestnet, zkSyncTestnet, zora, zoraSepolia, zircuitTestnet],
    connectors: [
        injected(),
        coinbaseWallet({ appName: "ioPlasmaVerse" }),
        metaMask({
            dappMetadata: {
                name: "ioPlasmaVerse",
                url: "https://your-dapp-url.com", // Replace with your dApp's URL
            },
        }),
    ],
    ssr: true,
    transports: {
        [mainnet.id]: http(),
    [sepolia.id]: http(),
    [polygon.id]: http(),
    [base.id]: http(),
    [baseSepolia.id]: http(),
    [iotex.id]: http(),
    [iotexTestnet.id]: http(),
    [acala.id]: http(),
    [ancient8.id]: http(),
    [ancient8Sepolia.id]: http(),
    [anvil.id]: http(),
    [apexTestnet.id]: http(),
    [arbitrum.id]: http(),
    [arbitrumGoerli.id]: http(),
    [arbitrumNova.id]: http(),
    [astar.id]: http(),
    [astarZkEVM.id]: http(),
    [astarZkyoto.id]: http(),
    [arbitrumSepolia.id]: http(),
    [areonNetwork.id]: http(),
    [areonNetworkTestnet.id]: http(),
    [artelaTestnet.id]: http(),
    [aurora.id]: http(),
    [auroraTestnet.id]: http(),
    [auroria.id]: http(),
    [avalanche.id]: http(),
    [avalancheFuji.id]: http(),
    [baseGoerli.id]: http(),

    [bahamut.id]: http(),
    [beam.id]: http(),
    [beamTestnet.id]: http(),
    [bearNetworkChainMainnet.id]: http(),
    [bearNetworkChainTestnet.id]: http(),
    [berachainTestnet.id]: http(),
    [berachainTestnetbArtio.id]: http(),
    [bevmMainnet.id]: http(),
    [bitkub.id]: http(),
    [bitkubTestnet.id]: http(),
    [bitTorrent.id]: http(),
    [bitTorrentTestnet.id]: http(),
    [blast.id]: http(),
    [blastSepolia.id]: http(),
    [bob.id]: http(),
    [boba.id]: http(),
    [bronos.id]: http(),
    [bronosTestnet.id]: http(),
    [bsc.id]: http(),
    [bscTestnet.id]: http(),
    [bscGreenfield.id]: http(),
    [btr.id]: http(),
    [btrTestnet.id]: http(),
    [bxn.id]: http(),
    [bxnTestnet.id]: http(),
    [canto.id]: http(),
    [celo.id]: http(),
    [celoAlfajores.id]: http(),
    [chiliz.id]: http(),
    [classic.id]: http(),
    [confluxESpace.id]: http(),
    [confluxESpaceTestnet.id]: http(),
    [coreDao.id]: http(),
    [crab.id]: http(),
    [cronos.id]: http(),
    [cronosTestnet.id]: http(),
    [crossbell.id]: http(),
    [cyber.id]: http(),
    [cyberTestnet.id]: http(),
    [darwinia.id]: http(),
    [dchain.id]: http(),
    [dchainTestnet.id]: http(),
    [defichainEvm.id]: http(),
    [defichainEvmTestnet.id]: http(),
    [degen.id]: http(),
    [dfk.id]: http(),
    [dodochainTestnet.id]: http(),
    [dogechain.id]: http(),
    [dreyerxMainnet.id]: http(),
    [edgeless.id]: http(),
    [edgelessTestnet.id]: http(),
    [edgeware.id]: http(),
    [edgewareTestnet.id]: http(),
    [eon.id]: http(),
    [eos.id]: http(),
    [eosTestnet.id]: http(),
    [etherlink.id]: http(),
    [etherlinkTestnet.id]: http(),
    [evmos.id]: http(),
    [evmosTestnet.id]: http(),
    [ekta.id]: http(),
    [ektaTestnet.id]: http(),
    [fantom.id]: http(),
    [fantomSonicTestnet.id]: http(),
    [fantomTestnet.id]: http(),
    [fibo.id]: http(),
    [filecoin.id]: http(),
    [filecoinCalibration.id]: http(),
    [filecoinHyperspace.id]: http(),
    [flare.id]: http(),
    [flareTestnet.id]: http(),
    [flowPreviewnet.id]: http(),
    [flowMainnet.id]: http(),
    [flowTestnet.id]: http(),
    [fraxtal.id]: http(),
    [fraxtalTestnet.id]: http(),
    [funkiSepolia.id]: http(),
    [fuse.id]: http(),
    [fuseSparknet.id]: http(),
    [jbc.id]: http(),
    [jbcTestnet.id]: http(),
    [karura.id]: http(),
    [gobi.id]: http(),
    [goerli.id]: http(),
    [gnosis.id]: http(),
    [gnosisChiado.id]: http(),
    [ham.id]: http(),
    [harmonyOne.id]: http(),
    [haqqMainnet.id]: http(),
    [haqqTestedge2.id]: http(),
    [hedera.id]: http(),
    [hederaTestnet.id]: http(),
    [hederaPreviewnet.id]: http(),
    [holesky.id]: http(),
    [immutableZkEvm.id]: http(),
    [immutableZkEvmTestnet.id]: http(),
    [inEVM.id]: http(),
    [kakarotSepolia.id]: http(),
    [kava.id]: http(),
    [kavaTestnet.id]: http(),
    [kcc.id]: http(),
    [klaytn.id]: http(),
    [klaytnBaobab.id]: http(),
    [koi.id]: http(),
    [kroma.id]: http(),
    [kromaSepolia.id]: http(),
    [l3x.id]: http(),
    [l3xTestnet.id]: http(),
    [lightlinkPegasus.id]: http(),
    [lightlinkPhoenix.id]: http(),
    [linea.id]: http(),
    [lineaGoerli.id]: http(),
    [lineaSepolia.id]: http(),
    [lisk.id]: http(),
    [liskSepolia.id]: http(),
    [localhost.id]: http(),
    [lukso.id]: http(),
    [luksoTestnet.id]: http(),
    [lycan.id]: http(),
    [lyra.id]: http(),
    [mandala.id]: http(),
    [manta.id]: http(),
    [mantaSepoliaTestnet.id]: http(),
    [mantaTestnet.id]: http(),
    [mantle.id]: http(),
    [mantleSepoliaTestnet.id]: http(),
    [mantleTestnet.id]: http(),
    [merlin.id]: http(),
    [metachain.id]: http(),
    [metachainIstanbul.id]: http(),
    [metalL2.id]: http(),
    [meter.id]: http(),
    [meterTestnet.id]: http(),
    [metis.id]: http(),
    [metisGoerli.id]: http(),
    [mev.id]: http(),
    [mevTestnet.id]: http(),
    [mintSepoliaTestnet.id]: http(),
    [mode.id]: http(),
    [modeTestnet.id]: http(),
    [moonbaseAlpha.id]: http(),
    [moonbeam.id]: http(),
    [moonbeamDev.id]: http(),
    [moonriver.id]: http(),
    [morphHolesky.id]: http(),
    [morphSepolia.id]: http(),
    [nautilus.id]: http(),
    [neonDevnet.id]: http(),
    [neonMainnet.id]: http(),
    [nexi.id]: http(),
    [nexilix.id]: http(),
    [oasys.id]: http(),
    [oasisTestnet.id]: http(),
    [okc.id]: http(),
    [optimism.id]: http(),
    [optimismGoerli.id]: http(),
    [optimismSepolia.id]: http(),
    [opBNB.id]: http(),
    [opBNBTestnet.id]: http(),
    [oortMainnetDev.id]: http(),
    [otimDevnet.id]: http(),
    [palm.id]: http(),
    [palmTestnet.id]: http(),
    [playfiAlbireo.id]: http(),
    [pgn.id]: http(),
    [pgnTestnet.id]: http(),
    [phoenix.id]: http(),
    [plinga.id]: http(),
    [plumeTestnet.id]: http(),
    [polygonAmoy.id]: http(),
    [polygonMumbai.id]: http(),
    [polygonZkEvm.id]: http(),
    [polygonZkEvmCardona.id]: http(),
    [polygonZkEvmTestnet.id]: http(),
    [pulsechain.id]: http(),
    [pulsechainV4.id]: http(),
    [qMainnet.id]: http(),
    [qTestnet.id]: http(),
    [real.id]: http(),
    [redbellyTestnet.id]: http(),
    [redstone.id]: http(),
    [reyaNetwork.id]: http(),
    [rollux.id]: http(),
    [rolluxTestnet.id]: http(),
    [ronin.id]: http(),
    [rootstock.id]: http(),
    [rootstockTestnet.id]: http(),
    [rss3.id]: http(),
    [rss3Sepolia.id]: http(),
    [sapphire.id]: http(),
    [sapphireTestnet.id]: http(),
    [satoshiVM.id]: http(),
    [satoshiVMTestnet.id]: http(),
    [scrollSepolia.id]: http(),
    [sei.id]: http(),
    [seiDevnet.id]: http(),
    [seiTestnet.id]: http(),
    [shimmer.id]: http(),
    [shimmerTestnet.id]: http(),
    [skaleBlockBrawlers.id]: http(),
    [skaleCalypso.id]: http(),
    [skaleCalypsoTestnet.id]: http(),
    [skaleCryptoBlades.id]: http(),
    [skaleCryptoColosseum.id]: http(),
    [skaleEuropa.id]: http(),
    [skaleEuropaTestnet.id]: http(),
    [skaleExorde.id]: http(),
    [skaleHumanProtocol.id]: http(),
    [skaleNebula.id]: http(),
    [skaleNebulaTestnet.id]: http(),
    [skaleRazor.id]: http(),
    [skaleTitan.id]: http(),
    [skaleTitanTestnet.id]: http(),
    [songbird.id]: http(),
    [songbirdTestnet.id]: http(),
    [spicy.id]: http(),
    [shardeumSphinx.id]: http(),
    [shibarium.id]: http(),
    [shibariumTestnet.id]: http(),
    [stratis.id]: http(),
    [syscoin.id]: http(),
    [syscoinTestnet.id]: http(),
    [taraxa.id]: http(),
    [taiko.id]: http(),
    [taikoHekla.id]: http(),
    [taikoJolnir.id]: http(),
    [taikoKatla.id]: http(),
    [taikoTestnetSepolia.id]: http(),
    [taraxaTestnet.id]: http(),
    [telcoinTestnet.id]: http(),
    [telos.id]: http(),
    [telosTestnet.id]: http(),
    [tenet.id]: http(),
    [thaiChain.id]: http(),
    [thunderTestnet.id]: http(),
    [unreal.id]: http(),
    [vechain.id]: http(),
    [wanchain.id]: http(),
    [wanchainTestnet.id]: http(),
    [wemix.id]: http(),
    [wemixTestnet.id]: http(),
    [xLayerTestnet.id]: http(),
    [xLayer.id]: http(),
    [xai.id]: http(),
    [xaiTestnet.id]: http(),
    [xdc.id]: http(),
    [xdcTestnet.id]: http(),
    [xrSepolia.id]: http(),
    [yooldoVerse.id]: http(),
    [yooldoVerseTestnet.id]: http(),
    [zetachain.id]: http(),
    [zetachainAthensTestnet.id]: http(),
    [zhejiang.id]: http(),
    [zilliqa.id]: http(),
    [zilliqaTestnet.id]: http(),
    [zkFair.id]: http(),
    [zkFairTestnet.id]: http(),
    [zkLinkNova.id]: http(),
    [zkLinkNovaSepoliaTestnet.id]: http(),
    [zkSync.id]: http(),
    [zkSyncInMemoryNode.id]: http(),
    [zkSyncLocalNode.id]: http(),
    [zkSyncSepoliaTestnet.id]: http(),
    [zkSyncTestnet.id]: http(),
    [zora.id]: http(),
    [zoraSepolia.id]: http(),
    [zircuitTestnet.id]: http(),
    },
});

declare module "wagmi" {
    interface Register {
        config: typeof config;
    }
}
