// imagePaths.js
export const imagePaths = {
accessories: [
    "/neurohacker/accessories/bandolier/Bandolier-icon0.png",
    "/neurohacker/accessories/bandolier/Bandolier-icon1.png",
    "/neurohacker/accessories/bandolier/Bandolier-icon2.png",
    "/neurohacker/accessories/bandolier/Bandolier-icon3.png",
    "/neurohacker/accessories/bandolier/Bandolier-icon4.png",
    "/neurohacker/accessories/bandolier/Bandolier-icon5.png",
    "/neurohacker/accessories/bandolier/Bandolier-icon6.png",
    "/neurohacker/accessories/bandolier.png",
    "/neurohacker/accessories/beltandbag/Beltandbag-icon0.png",
    "/neurohacker/accessories/beltandbag/Beltandbag-icon1.png",
    "/neurohacker/accessories/beltandbag/Beltandbag-icon2.png",
    "/neurohacker/accessories/beltandbag/Beltandbag-icon3.png",
    "/neurohacker/accessories/beltandbag/Beltandbag-icon4.png",
    "/neurohacker/accessories/beltandbag/Beltandbag-icon5.png",
    "/neurohacker/accessories/beltandbag/Beltandbag-icon6.png",
    "/neurohacker/accessories/beltandbag.png",
    "/neurohacker/accessories/chestrig/Chestrig-icon0.png",
    "/neurohacker/accessories/chestrig/Chestrig-icon1.png",
    "/neurohacker/accessories/chestrig/Chestrig-icon2.png",
    "/neurohacker/accessories/chestrig/Chestrig-icon3.png",
    "/neurohacker/accessories/chestrig/Chestrig-icon4.png",
    "/neurohacker/accessories/chestrig/Chestrig-icon5.png",
    "/neurohacker/accessories/chestrig/Chestrig-icon6.png",
    "/neurohacker/accessories/chestrig.png",
    "/neurohacker/accessories/combatgloves/Combat Gloves-icon0.png",
    "/neurohacker/accessories/combatgloves/Combat Gloves-icon1.png",
    "/neurohacker/accessories/combatgloves/Combat Gloves-icon2.png",
    "/neurohacker/accessories/combatgloves/Combat Gloves-icon3.png",
    "/neurohacker/accessories/combatgloves/Combat Gloves-icon4.png",
    "/neurohacker/accessories/combatgloves/Combat Gloves-icon5.png",
    "/neurohacker/accessories/combatgloves/Combat Gloves-icon6.png",
    "/neurohacker/accessories/combatgloves.png",
    "/neurohacker/accessories/fingergloves/Fingergloves-icon0.png",
    "/neurohacker/accessories/fingergloves/Fingergloves-icon1.png",
    "/neurohacker/accessories/fingergloves/Fingergloves-icon2.png",
    "/neurohacker/accessories/fingergloves/Fingergloves-icon3.png",
    "/neurohacker/accessories/fingergloves/Fingergloves-icon4.png",
    "/neurohacker/accessories/fingergloves/Fingergloves-icon5.png",
    "/neurohacker/accessories/fingergloves/Fingergloves-icon6.png",
    "/neurohacker/accessories/fingergloves.png",
    "/neurohacker/accessories/legbandages/Legbandages-icon0.png",
    "/neurohacker/accessories/legbandages/Legbandages-icon1.png",
    "/neurohacker/accessories/legbandages/Legbandages-icon2.png",
    "/neurohacker/accessories/legbandages/Legbandages-icon3.png",
    "/neurohacker/accessories/legbandages/Legbandages-icon4.png",
    "/neurohacker/accessories/legbandages/Legbandages-icon5.png",
    "/neurohacker/accessories/legbandages/Legbandages-icon6.png",
    "/neurohacker/accessories/legbandages.png",
    "/neurohacker/accessories/ninjagloves/Ninjagloves-icon0.png",
    "/neurohacker/accessories/ninjagloves/Ninjagloves-icon1.png",
    "/neurohacker/accessories/ninjagloves/Ninjagloves-icon2.png",
    "/neurohacker/accessories/ninjagloves/Ninjagloves-icon3.png",
    "/neurohacker/accessories/ninjagloves/Ninjagloves-icon4.png",
    "/neurohacker/accessories/ninjagloves/Ninjagloves-icon5.png",
    "/neurohacker/accessories/ninjagloves/Ninjagloves-icon6.png",
    "/neurohacker/accessories/ninjagloves.png"
  ],
  body: [
    "/neurohacker/body/neurohacker.png",
    "/neurohacker/body/skin/original-gloves.png",
    "/neurohacker/body/skin/original-long-socks.png",
    "/neurohacker/body/skin/original-socks.png",
    "/neurohacker/body/skin/original.png",
    "/neurohacker/body/skin/skin1-gloves.png",
    "/neurohacker/body/skin/skin1-long-socks.png",
    "/neurohacker/body/skin/skin1-socks.png",
    "/neurohacker/body/skin/skin1.png",
    "/neurohacker/body/skin/skin2-gloves.png",
    "/neurohacker/body/skin/skin2-long-socks.png",
    "/neurohacker/body/skin/skin2-socks.png",
    "/neurohacker/body/skin/skin2.png",
    "/neurohacker/body/skin/skin3-gloves.png",
    "/neurohacker/body/skin/skin3-long-socks.png",
    "/neurohacker/body/skin/skin3-socks.png",
    "/neurohacker/body/skin/skin3.png",
    "/neurohacker/body/skin/skin4-gloves.png",
    "/neurohacker/body/skin/skin4-long-socks.png",
    "/neurohacker/body/skin/skin4-socks.png",
    "/neurohacker/body/skin/skin4.png"
  ],
  chest: [
    "/neurohacker/chest/combatvest/Combat Vest-icon0.png",
    "/neurohacker/chest/combatvest/Combat Vest-icon1.png",
    "/neurohacker/chest/combatvest/Combat Vest-icon2.png",
    "/neurohacker/chest/combatvest/Combat Vest-icon3.png",
    "/neurohacker/chest/combatvest/Combat Vest-icon4.png",
    "/neurohacker/chest/combatvest/Combat Vest-icon5.png",
    "/neurohacker/chest/combatvest/Combat Vest-icon6.png",
    "/neurohacker/chest/combatvest.png",
    "/neurohacker/chest/dressjacket/Dressjacket-icon0.png",
    "/neurohacker/chest/dressjacket/Dressjacket-icon1.png",
    "/neurohacker/chest/dressjacket/Dressjacket-icon2.png",
    "/neurohacker/chest/dressjacket/Dressjacket-icon3.png",
    "/neurohacker/chest/dressjacket/Dressjacket-icon4.png",
    "/neurohacker/chest/dressjacket/Dressjacket-icon5.png",
    "/neurohacker/chest/dressjacket/Dressjacket-icon6.png",
    "/neurohacker/chest/dressjacket.png",
    "/neurohacker/chest/dressrobe/Dressrobe-icon0.png",
    "/neurohacker/chest/dressrobe/Dressrobe-icon1.png",
    "/neurohacker/chest/dressrobe/Dressrobe-icon2.png",
    "/neurohacker/chest/dressrobe/Dressrobe-icon3.png",
    "/neurohacker/chest/dressrobe/Dressrobe-icon4.png",
    "/neurohacker/chest/dressrobe/Dressrobe-icon5.png",
    "/neurohacker/chest/dressrobe/Dressrobe-icon6.png",
    "/neurohacker/chest/dressrobe.png",
    "/neurohacker/chest/fancysuit/Fancy Suit-icon0.png",
    "/neurohacker/chest/fancysuit/Fancy Suit-icon1.png",
    "/neurohacker/chest/fancysuit/Fancy Suit-icon2.png",
    "/neurohacker/chest/fancysuit/Fancy Suit-icon3.png",
    "/neurohacker/chest/fancysuit/Fancy Suit-icon4.png",
    "/neurohacker/chest/fancysuit/Fancy Suit-icon5.png",
    "/neurohacker/chest/fancysuit/Fancy Suit-icon6.png",
    "/neurohacker/chest/fancysuit.png",
    "/neurohacker/chest/fulljacket/Fulljacket-icon0.png",
    "/neurohacker/chest/fulljacket/Fulljacket-icon1.png",
    "/neurohacker/chest/fulljacket/Fulljacket-icon2.png",
    "/neurohacker/chest/fulljacket/Fulljacket-icon3.png",
    "/neurohacker/chest/fulljacket/Fulljacket-icon4.png",
    "/neurohacker/chest/fulljacket/Fulljacket-icon5.png",
    "/neurohacker/chest/fulljacket/Fulljacket-icon6.png",
    "/neurohacker/chest/fulljacket.png",
    "/neurohacker/chest/logotee/Logo Tee-icon0.png",
    "/neurohacker/chest/logotee/Logo Tee-icon1.png",
    "/neurohacker/chest/logotee/Logo Tee-icon2.png",
    "/neurohacker/chest/logotee/Logo Tee-icon3.png",
    "/neurohacker/chest/logotee/Logo Tee-icon4.png",
    "/neurohacker/chest/logotee/Logo Tee-icon5.png",
    "/neurohacker/chest/logotee/Logo Tee-icon6.png",
    "/neurohacker/chest/logotee.png",
    "/neurohacker/chest/simpleshirt/Simple Shirt-icon0.png",
    "/neurohacker/chest/simpleshirt/Simple Shirt-icon1.png",
    "/neurohacker/chest/simpleshirt/Simple Shirt-icon2.png",
    "/neurohacker/chest/simpleshirt/Simple Shirt-icon3.png",
    "/neurohacker/chest/simpleshirt/Simple Shirt-icon4.png",
    "/neurohacker/chest/simpleshirt/Simple Shirt-icon5.png",
    "/neurohacker/chest/simpleshirt/Simple Shirt-icon6.png",
    "/neurohacker/chest/simpleshirt.png",
    "/neurohacker/chest/slottedshirt/Slottedshirt-icon0.png",
    "/neurohacker/chest/slottedshirt/Slottedshirt-icon1.png",
    "/neurohacker/chest/slottedshirt/Slottedshirt-icon2.png",
    "/neurohacker/chest/slottedshirt/Slottedshirt-icon3.png",
    "/neurohacker/chest/slottedshirt/Slottedshirt-icon4.png",
    "/neurohacker/chest/slottedshirt/Slottedshirt-icon5.png",
    "/neurohacker/chest/slottedshirt/Slottedshirt-icon6.png",
    "/neurohacker/chest/slottedshirt.png",
    "/neurohacker/chest/streetware/Streetware-icon0.png",
    "/neurohacker/chest/streetware/Streetware-icon1.png",
    "/neurohacker/chest/streetware/Streetware-icon2.png",
    "/neurohacker/chest/streetware/Streetware-icon3.png",
    "/neurohacker/chest/streetware/Streetware-icon4.png",
    "/neurohacker/chest/streetware/Streetware-icon5.png",
    "/neurohacker/chest/streetware/Streetware-icon6.png",
    "/neurohacker/chest/streetware.png",
    "/neurohacker/chest/sweater/Sweater-icon0.png",
    "/neurohacker/chest/sweater/Sweater-icon1.png",
    "/neurohacker/chest/sweater/Sweater-icon2.png",
    "/neurohacker/chest/sweater/Sweater-icon3.png",
    "/neurohacker/chest/sweater/Sweater-icon4.png",
    "/neurohacker/chest/sweater/Sweater-icon5.png",
    "/neurohacker/chest/sweater/Sweater-icon6.png",
    "/neurohacker/chest/sweater.png"
  ],
  eyes: [
    "/neurohacker/eyes/color/eyes-icon0.png",
    "/neurohacker/eyes/color/eyes-icon1.png",
    "/neurohacker/eyes/color/eyes-icon10.png",
    "/neurohacker/eyes/color/eyes-icon11.png",
    "/neurohacker/eyes/color/eyes-icon12.png",
    "/neurohacker/eyes/color/eyes-icon13.png",
    "/neurohacker/eyes/color/eyes-icon14.png",
    "/neurohacker/eyes/color/eyes-icon15.png",
    "/neurohacker/eyes/color/eyes-icon16.png",
    "/neurohacker/eyes/color/eyes-icon17.png",
    "/neurohacker/eyes/color/eyes-icon18.png",
    "/neurohacker/eyes/color/eyes-icon19.png",
    "/neurohacker/eyes/color/eyes-icon2.png",
    "/neurohacker/eyes/color/eyes-icon20.png",
    "/neurohacker/eyes/color/eyes-icon21.png",
    "/neurohacker/eyes/color/eyes-icon22.png",
    "/neurohacker/eyes/color/eyes-icon23.png",
    "/neurohacker/eyes/color/eyes-icon24.png",
    "/neurohacker/eyes/color/eyes-icon25.png",
    "/neurohacker/eyes/color/eyes-icon26.png",
    "/neurohacker/eyes/color/eyes-icon27.png",
    "/neurohacker/eyes/color/eyes-icon28.png",
    "/neurohacker/eyes/color/eyes-icon29.png",
    "/neurohacker/eyes/color/eyes-icon3.png",
    "/neurohacker/eyes/color/eyes-icon30.png",
    "/neurohacker/eyes/color/eyes-icon31.png",
    "/neurohacker/eyes/color/eyes-icon4.png",
    "/neurohacker/eyes/color/eyes-icon5.png",
    "/neurohacker/eyes/color/eyes-icon6.png",
    "/neurohacker/eyes/color/eyes-icon7.png",
    "/neurohacker/eyes/color/eyes-icon8.png",
    "/neurohacker/eyes/color/eyes-icon9.png",
    "/neurohacker/eyes/regulareyes.png"
  ],
  foot: [
    "/neurohacker/foot/boots/Boots-icon0.png",
    "/neurohacker/foot/boots/Boots-icon1.png",
    "/neurohacker/foot/boots/Boots-icon2.png",
    "/neurohacker/foot/boots/Boots-icon3.png",
    "/neurohacker/foot/boots/Boots-icon4.png",
    "/neurohacker/foot/boots/Boots-icon5.png",
    "/neurohacker/foot/boots/Boots-icon6.png",
    "/neurohacker/foot/boots.png",
    "/neurohacker/foot/dressshoes/Dressshoes-icon0.png",
    "/neurohacker/foot/dressshoes/Dressshoes-icon1.png",
    "/neurohacker/foot/dressshoes/Dressshoes-icon2.png",
    "/neurohacker/foot/dressshoes/Dressshoes-icon3.png",
    "/neurohacker/foot/dressshoes/Dressshoes-icon4.png",
    "/neurohacker/foot/dressshoes/Dressshoes-icon5.png",
    "/neurohacker/foot/dressshoes/Dressshoes-icon6.png",
    "/neurohacker/foot/dressshoes.png",
    "/neurohacker/foot/fantasyboots/Fantasyboots-icon0.png",
    "/neurohacker/foot/fantasyboots/Fantasyboots-icon1.png",
    "/neurohacker/foot/fantasyboots/Fantasyboots-icon2.png",
    "/neurohacker/foot/fantasyboots/Fantasyboots-icon3.png",
    "/neurohacker/foot/fantasyboots/Fantasyboots-icon4.png",
    "/neurohacker/foot/fantasyboots/Fantasyboots-icon5.png",
    "/neurohacker/foot/fantasyboots/Fantasyboots-icon6.png",
    "/neurohacker/foot/fantasyboots.png",
    "/neurohacker/foot/hikingboots/Hikingboots-icon0.png",
    "/neurohacker/foot/hikingboots/Hikingboots-icon1.png",
    "/neurohacker/foot/hikingboots/Hikingboots-icon2.png",
    "/neurohacker/foot/hikingboots/Hikingboots-icon3.png",
    "/neurohacker/foot/hikingboots/Hikingboots-icon4.png",
    "/neurohacker/foot/hikingboots/Hikingboots-icon5.png",
    "/neurohacker/foot/hikingboots/Hikingboots-icon6.png",
    "/neurohacker/foot/hikingboots.png",
    "/neurohacker/foot/runningshoes/Runningshoes-icon0.png",
    "/neurohacker/foot/runningshoes/Runningshoes-icon1.png",
    "/neurohacker/foot/runningshoes/Runningshoes-icon2.png",
    "/neurohacker/foot/runningshoes/Runningshoes-icon3.png",
    "/neurohacker/foot/runningshoes/Runningshoes-icon4.png",
    "/neurohacker/foot/runningshoes/Runningshoes-icon5.png",
    "/neurohacker/foot/runningshoes/Runningshoes-icon6.png",
    "/neurohacker/foot/runningshoes.png",
    "/neurohacker/foot/shroudedboots/Shroudedboots-icon0.png",
    "/neurohacker/foot/shroudedboots/Shroudedboots-icon1.png",
    "/neurohacker/foot/shroudedboots/Shroudedboots-icon2.png",
    "/neurohacker/foot/shroudedboots/Shroudedboots-icon3.png",
    "/neurohacker/foot/shroudedboots/Shroudedboots-icon4.png",
    "/neurohacker/foot/shroudedboots/Shroudedboots-icon5.png",
    "/neurohacker/foot/shroudedboots/Shroudedboots-icon6.png",
    "/neurohacker/foot/shroudedboots.png",
    "/neurohacker/foot/simpleshoes/Simple Shoes-icon0.png",
    "/neurohacker/foot/simpleshoes/Simple Shoes-icon1.png",
    "/neurohacker/foot/simpleshoes/Simple Shoes-icon2.png",
    "/neurohacker/foot/simpleshoes/Simple Shoes-icon3.png",
    "/neurohacker/foot/simpleshoes/Simple Shoes-icon4.png",
    "/neurohacker/foot/simpleshoes/Simple Shoes-icon5.png",
    "/neurohacker/foot/simpleshoes/Simple Shoes-icon6.png",
    "/neurohacker/foot/simpleshoes.png",
    "/neurohacker/foot/sinchboots/Sinch Boots-icon0.png",
    "/neurohacker/foot/sinchboots/Sinch Boots-icon1.png",
    "/neurohacker/foot/sinchboots/Sinch Boots-icon2.png",
    "/neurohacker/foot/sinchboots/Sinch Boots-icon3.png",
    "/neurohacker/foot/sinchboots/Sinch Boots-icon4.png",
    "/neurohacker/foot/sinchboots/Sinch Boots-icon5.png",
    "/neurohacker/foot/sinchboots/Sinch Boots-icon6.png",
    "/neurohacker/foot/sinchboots.png",
    "/neurohacker/foot/strapedboots/Straped Boots-icon0.png",
    "/neurohacker/foot/strapedboots/Straped Boots-icon1.png",
    "/neurohacker/foot/strapedboots/Straped Boots-icon2.png",
    "/neurohacker/foot/strapedboots/Straped Boots-icon3.png",
    "/neurohacker/foot/strapedboots/Straped Boots-icon4.png",
    "/neurohacker/foot/strapedboots/Straped Boots-icon5.png",
    "/neurohacker/foot/strapedboots/Straped Boots-icon6.png",
    "/neurohacker/foot/strapedboots.png",
    "/neurohacker/foot/tallboots/Tallboots-icon0.png",
    "/neurohacker/foot/tallboots/Tallboots-icon1.png",
    "/neurohacker/foot/tallboots/Tallboots-icon2.png",
    "/neurohacker/foot/tallboots/Tallboots-icon3.png",
    "/neurohacker/foot/tallboots/Tallboots-icon4.png",
    "/neurohacker/foot/tallboots/Tallboots-icon5.png",
    "/neurohacker/foot/tallboots/Tallboots-icon6.png",
    "/neurohacker/foot/tallboots.png"
  ],
  head: [
    "/neurohacker/head/braided.png",
    "/neurohacker/head/hair1.png",
    "/neurohacker/head/hair2.png",
    "/neurohacker/head/hair3.png",
    "/neurohacker/head/hair4.png",
    "/neurohacker/head/hair5.png",
    "/neurohacker/head/hairshort.png",
    "/neurohacker/head/short.png",
    "/neurohacker/head/straight.png",
    "/neurohacker/head/straightdown.png"
  ],
  legs: [
    "/neurohacker/legs/cargopants/Cargo Pants-icon0.png",
    "/neurohacker/legs/cargopants/Cargo Pants-icon1.png",
    "/neurohacker/legs/cargopants/Cargo Pants-icon2.png",
    "/neurohacker/legs/cargopants/Cargo Pants-icon3.png",
    "/neurohacker/legs/cargopants/Cargo Pants-icon4.png",
    "/neurohacker/legs/cargopants/Cargo Pants-icon5.png",
    "/neurohacker/legs/cargopants/Cargo Pants-icon6.png",
    "/neurohacker/legs/cargopants.png",
    "/neurohacker/legs/cargoshorts/Cargoshorts-icon0.png",
    "/neurohacker/legs/cargoshorts/Cargoshorts-icon1.png",
    "/neurohacker/legs/cargoshorts/Cargoshorts-icon2.png",
    "/neurohacker/legs/cargoshorts/Cargoshorts-icon3.png",
    "/neurohacker/legs/cargoshorts/Cargoshorts-icon4.png",
    "/neurohacker/legs/cargoshorts/Cargoshorts-icon5.png",
    "/neurohacker/legs/cargoshorts/Cargoshorts-icon6.png",
    "/neurohacker/legs/cargoshorts.png",
    "/neurohacker/legs/rolleduppants/Rolleduppants-icon0.png",
    "/neurohacker/legs/rolleduppants/Rolleduppants-icon1.png",
    "/neurohacker/legs/rolleduppants/Rolleduppants-icon2.png",
    "/neurohacker/legs/rolleduppants/Rolleduppants-icon3.png",
    "/neurohacker/legs/rolleduppants/Rolleduppants-icon4.png",
    "/neurohacker/legs/rolleduppants/Rolleduppants-icon5.png",
    "/neurohacker/legs/rolleduppants/Rolleduppants-icon6.png",
    "/neurohacker/legs/rolleduppants.png",
    "/neurohacker/legs/shorts/Shorts-icon0.png",
    "/neurohacker/legs/shorts/Shorts-icon1.png",
    "/neurohacker/legs/shorts/Shorts-icon2.png",
    "/neurohacker/legs/shorts/Shorts-icon3.png",
    "/neurohacker/legs/shorts/Shorts-icon4.png",
    "/neurohacker/legs/shorts/Shorts-icon5.png",
    "/neurohacker/legs/shorts/Shorts-icon6.png",
    "/neurohacker/legs/shorts.png",
    "/neurohacker/legs/shortsandsweats/Shortsandsweats-icon0.png",
    "/neurohacker/legs/shortsandsweats/Shortsandsweats-icon1.png",
    "/neurohacker/legs/shortsandsweats/Shortsandsweats-icon2.png",
    "/neurohacker/legs/shortsandsweats/Shortsandsweats-icon3.png",
    "/neurohacker/legs/shortsandsweats/Shortsandsweats-icon4.png",
    "/neurohacker/legs/shortsandsweats/Shortsandsweats-icon5.png",
    "/neurohacker/legs/shortsandsweats/Shortsandsweats-icon6.png",
    "/neurohacker/legs/shortsandsweats.png",
    "/neurohacker/legs/streetpants/Streetpants-icon0.png",
    "/neurohacker/legs/streetpants/Streetpants-icon1.png",
    "/neurohacker/legs/streetpants/Streetpants-icon2.png",
    "/neurohacker/legs/streetpants/Streetpants-icon3.png",
    "/neurohacker/legs/streetpants/Streetpants-icon4.png",
    "/neurohacker/legs/streetpants/Streetpants-icon5.png",
    "/neurohacker/legs/streetpants/Streetpants-icon6.png",
    "/neurohacker/legs/streetpants.png",
    "/neurohacker/legs/suitpants/Suitpants-icon0.png",
    "/neurohacker/legs/suitpants/Suitpants-icon1.png",
    "/neurohacker/legs/suitpants/Suitpants-icon2.png",
    "/neurohacker/legs/suitpants/Suitpants-icon3.png",
    "/neurohacker/legs/suitpants/Suitpants-icon4.png",
    "/neurohacker/legs/suitpants/Suitpants-icon5.png",
    "/neurohacker/legs/suitpants/Suitpants-icon6.png",
    "/neurohacker/legs/suitpants.png",
    "/neurohacker/legs/tightjeans/Tightjeans-icon0.png",
    "/neurohacker/legs/tightjeans/Tightjeans-icon1.png",
    "/neurohacker/legs/tightjeans/Tightjeans-icon2.png",
    "/neurohacker/legs/tightjeans/Tightjeans-icon3.png",
    "/neurohacker/legs/tightjeans/Tightjeans-icon4.png",
    "/neurohacker/legs/tightjeans/Tightjeans-icon5.png",
    "/neurohacker/legs/tightjeans/Tightjeans-icon6.png",
    "/neurohacker/legs/tightjeans.png",
    "/neurohacker/legs/workingpants/Working Pants-icon0.png",
    "/neurohacker/legs/workingpants/Working Pants-icon1.png",
    "/neurohacker/legs/workingpants/Working Pants-icon2.png",
    "/neurohacker/legs/workingpants/Working Pants-icon3.png",
    "/neurohacker/legs/workingpants/Working Pants-icon4.png",
    "/neurohacker/legs/workingpants/Working Pants-icon5.png",
    "/neurohacker/legs/workingpants/Working Pants-icon6.png",
    "/neurohacker/legs/workingpants.png"
  ],
  outer: [
    "/neurohacker/outer/longjacket/Longjacket-icon0.png",
    "/neurohacker/outer/longjacket/Longjacket-icon1.png",
    "/neurohacker/outer/longjacket/Longjacket-icon2.png",
    "/neurohacker/outer/longjacket/Longjacket-icon3.png",
    "/neurohacker/outer/longjacket/Longjacket-icon4.png",
    "/neurohacker/outer/longjacket/Longjacket-icon5.png",
    "/neurohacker/outer/longjacket/Longjacket-icon6.png",
    "/neurohacker/outer/longjacket.png",
    "/neurohacker/outer/robe/Robe-icon0.png",
    "/neurohacker/outer/robe/Robe-icon1.png",
    "/neurohacker/outer/robe/Robe-icon2.png",
    "/neurohacker/outer/robe/Robe-icon3.png",
    "/neurohacker/outer/robe/Robe-icon4.png",
    "/neurohacker/outer/robe/Robe-icon5.png",
    "/neurohacker/outer/robe/Robe-icon6.png",
    "/neurohacker/outer/robe.png"
  ],
  _textureCollections: [
    "/neurohacker/_textureCollections/eyes/IMG_2857.png",
    "/neurohacker/_textureCollections/eyes/IMG_2858.png",
    "/neurohacker/_textureCollections/eyes/IMG_2859.png",
    "/neurohacker/_textureCollections/eyes/IMG_2860.png",
    "/neurohacker/_textureCollections/eyes/IMG_2861.png",
    "/neurohacker/_textureCollections/eyes/IMG_2862.png",
    "/neurohacker/_textureCollections/eyes/IMG_2863.png",
    "/neurohacker/_textureCollections/eyes/IMG_2864.png",
    "/neurohacker/_textureCollections/eyes/IMG_2865.png",
    "/neurohacker/_textureCollections/eyes/IMG_2866.png",
    "/neurohacker/_textureCollections/eyes/IMG_2867.png",
    "/neurohacker/_textureCollections/eyes/IMG_2868.png",
    "/neurohacker/_textureCollections/eyes/IMG_2869.png",
    "/neurohacker/_textureCollections/eyes/IMG_2870.png",
    "/neurohacker/_textureCollections/eyes/IMG_2871.png",
    "/neurohacker/_textureCollections/eyes/IMG_2872.png",
    "/neurohacker/_textureCollections/eyes/IMG_2874.png",
    "/neurohacker/_textureCollections/eyes/IMG_2875.png",
    "/neurohacker/_textureCollections/eyes/IMG_2876.png",
    "/neurohacker/_textureCollections/eyes/IMG_2877.png",
    "/neurohacker/_textureCollections/eyes/IMG_2878.png",
    "/neurohacker/_textureCollections/eyes/IMG_2879.png",
    "/neurohacker/_textureCollections/eyes/IMG_2880.png",
    "/neurohacker/_textureCollections/eyes/IMG_2881.png",
    "/neurohacker/_textureCollections/eyes/IMG_2882.png",
    "/neurohacker/_textureCollections/eyes/IMG_2883.png",
    "/neurohacker/_textureCollections/eyes/IMG_2884.png",
    "/neurohacker/_textureCollections/eyes/IMG_2885.png",
    "/neurohacker/_textureCollections/eyes/IMG_2886.png",
    "/neurohacker/_textureCollections/eyes/IMG_2887.png",
    "/neurohacker/_textureCollections/eyes/IMG_2888.png",
    "/neurohacker/_textureCollections/eyes/IMG_2889.png",
    "/neurohacker/_textureCollections/outfit_1/outfit_1_0.png",
    "/neurohacker/_textureCollections/outfit_1/outfit_1_1.png",
    "/neurohacker/_textureCollections/outfit_1/outfit_1_2.png",
    "/neurohacker/_textureCollections/outfit_1/outfit_1_3.png",
    "/neurohacker/_textureCollections/outfit_1/outfit_1_4.png",
    "/neurohacker/_textureCollections/outfit_1/outfit_1_5.png",
    "/neurohacker/_textureCollections/outfit_1/outfit_1_6.png",
    "/neurohacker/_textureCollections/outfit_10/outfit_10_0.png",
    "/neurohacker/_textureCollections/outfit_10/outfit_10_1.png",
    "/neurohacker/_textureCollections/outfit_10/outfit_10_2.png",
    "/neurohacker/_textureCollections/outfit_10/outfit_10_3.png",
    "/neurohacker/_textureCollections/outfit_10/outfit_10_4.png",
    "/neurohacker/_textureCollections/outfit_10/outfit_10_5.png",
    "/neurohacker/_textureCollections/outfit_10/outfit_10_6.png",
    "/neurohacker/_textureCollections/outfit_2/outfit_2_0.png",
    "/neurohacker/_textureCollections/outfit_2/outfit_2_1.png",
    "/neurohacker/_textureCollections/outfit_2/outfit_2_2.png",
    "/neurohacker/_textureCollections/outfit_2/outfit_2_3.png",
    "/neurohacker/_textureCollections/outfit_2/outfit_2_4.png",
    "/neurohacker/_textureCollections/outfit_2/outfit_2_5.png",
    "/neurohacker/_textureCollections/outfit_2/outfit_2_6.png",
    "/neurohacker/_textureCollections/outfit_3/outfit_3_0.png",
    "/neurohacker/_textureCollections/outfit_3/outfit_3_1.png",
    "/neurohacker/_textureCollections/outfit_3/outfit_3_2.png",
    "/neurohacker/_textureCollections/outfit_3/outfit_3_3.png",
    "/neurohacker/_textureCollections/outfit_3/outfit_3_4.png",
    "/neurohacker/_textureCollections/outfit_3/outfit_3_5.png",
    "/neurohacker/_textureCollections/outfit_3/outfit_3_6.png",
    "/neurohacker/_textureCollections/outfit_4/outfit_4_0.png",
    "/neurohacker/_textureCollections/outfit_4/outfit_4_1.png",
    "/neurohacker/_textureCollections/outfit_4/outfit_4_2.png",
    "/neurohacker/_textureCollections/outfit_4/outfit_4_3.png",
    "/neurohacker/_textureCollections/outfit_4/outfit_4_4.png",
    "/neurohacker/_textureCollections/outfit_4/outfit_4_5.png",
    "/neurohacker/_textureCollections/outfit_4/outfit_4_6.png",
    "/neurohacker/_textureCollections/outfit_5/outfit_5_0.png",
    "/neurohacker/_textureCollections/outfit_5/outfit_5_1.png",
    "/neurohacker/_textureCollections/outfit_5/outfit_5_2.png",
    "/neurohacker/_textureCollections/outfit_5/outfit_5_3.png",
    "/neurohacker/_textureCollections/outfit_5/outfit_5_4.png",
    "/neurohacker/_textureCollections/outfit_5/outfit_5_5.png",
    "/neurohacker/_textureCollections/outfit_5/outfit_5_6.png",
    "/neurohacker/_textureCollections/outfit_6/outfit_6_0.png",
    "/neurohacker/_textureCollections/outfit_6/outfit_6_1.png",
    "/neurohacker/_textureCollections/outfit_6/outfit_6_2.png",
    "/neurohacker/_textureCollections/outfit_6/outfit_6_3.png",
    "/neurohacker/_textureCollections/outfit_6/outfit_6_4.png",
    "/neurohacker/_textureCollections/outfit_6/outfit_6_5.png",
    "/neurohacker/_textureCollections/outfit_6/outfit_6_6.png",
    "/neurohacker/_textureCollections/outfit_7/outfit_7_0.png",
    "/neurohacker/_textureCollections/outfit_7/outfit_7_1.png",
    "/neurohacker/_textureCollections/outfit_7/outfit_7_2.png",
    "/neurohacker/_textureCollections/outfit_7/outfit_7_3.png",
    "/neurohacker/_textureCollections/outfit_7/outfit_7_4.png",
    "/neurohacker/_textureCollections/outfit_7/outfit_7_5.png",
    "/neurohacker/_textureCollections/outfit_7/outfit_7_6.png",
    "/neurohacker/_textureCollections/outfit_8/outfit_8_0.png",
    "/neurohacker/_textureCollections/outfit_8/outfit_8_1.png",
    "/neurohacker/_textureCollections/outfit_8/outfit_8_2.png",
    "/neurohacker/_textureCollections/outfit_8/outfit_8_3.png",
    "/neurohacker/_textureCollections/outfit_8/outfit_8_4.png",
    "/neurohacker/_textureCollections/outfit_8/outfit_8_5.png",
    "/neurohacker/_textureCollections/outfit_8/outfit_8_6.png",
    "/neurohacker/_textureCollections/outfit_9/outfit_9_0.png",
    "/neurohacker/_textureCollections/outfit_9/outfit_9_1.png",
    "/neurohacker/_textureCollections/outfit_9/outfit_9_2.png",
    "/neurohacker/_textureCollections/outfit_9/outfit_9_3.png",
    "/neurohacker/_textureCollections/outfit_9/outfit_9_4.png",
    "/neurohacker/_textureCollections/outfit_9/outfit_9_5.png",
    "/neurohacker/_textureCollections/outfit_9/outfit_9_6.png",
    "/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_Face_BaseColor.png",
    "/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_Face_BaseColor1.png",
    "/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_Face_BaseColor2.png",
    "/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_Face_BaseColor3.png",
    "/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_Face_BaseColor4.png",
    "/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_Face_BaseColor_alt.png",
    "/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_skin_BaseColor.png",
    "/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_skin_BaseColor1.png",
    "/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_skin_BaseColor2.png",
    "/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_skin_BaseColor3.png",
    "/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_skin_BaseColor4.png",
    "/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_skin_BaseColor_alt.png",
    "/neurohacker/_textureCollections/skin/ArmSleeves_Original.png",
    "/neurohacker/_textureCollections/skin/ArmSleeves_Tone_1.png",
    "/neurohacker/_textureCollections/skin/ArmSleeves_Tone_2.png",
    "/neurohacker/_textureCollections/skin/ArmSleeves_Tone_3.png",
    "/neurohacker/_textureCollections/skin/ArmSleeves_Tone_4.png",
    "/neurohacker/_textureCollections/skin/KneeHighs_Original.png",
    "/neurohacker/_textureCollections/skin/KneeHighs_Tone_1.png",
    "/neurohacker/_textureCollections/skin/KneeHighs_Tone_2.png",
    "/neurohacker/_textureCollections/skin/KneeHighs_Tone_3.png",
    "/neurohacker/_textureCollections/skin/KneeHighs_Tone_4.png",
    "/neurohacker/_textureCollections/skin/original_mouth.png",
    "/neurohacker/_textureCollections/skin/skin1_mouth.png",
    "/neurohacker/_textureCollections/skin/skin2_mouth.png",
    "/neurohacker/_textureCollections/skin/skin3_mouth.png",
    "/neurohacker/_textureCollections/skin/skin4_mouth.png",
    "/neurohacker/_textureCollections/skin/ThighHighs_Original.png",
    "/neurohacker/_textureCollections/skin/ThighHighs_Tone_1.png",
    "/neurohacker/_textureCollections/skin/ThighHighs_Tone_2.png",
    "/neurohacker/_textureCollections/skin/ThighHighs_Tone_3.png",
    "/neurohacker/_textureCollections/skin/ThighHighs_Tone_4.png"
  ]
};
export const imagePathsvrm = {   accessories: [
  "/neurohacker/accessories/bandolier.vrm",
  "/neurohacker/accessories/beltandbag.vrm",
  "/neurohacker/accessories/chestrig.vrm",
  "/neurohacker/accessories/combatgloves.vrm",
  "/neurohacker/accessories/fingergloves.vrm",
  "/neurohacker/accessories/legbandages.vrm",
  "/neurohacker/accessories/ninjagloves.vrm"
],
body: [
  "/neurohacker/body/neurohacker.vrm"
],
chest: [
  "/neurohacker/chest/combatvest.vrm",
  "/neurohacker/chest/dressjacket.vrm",
  "/neurohacker/chest/dressrobe.vrm",
  "/neurohacker/chest/fancysuit.vrm",
  "/neurohacker/chest/fulljacket.vrm",
  "/neurohacker/chest/logotee.vrm",
  "/neurohacker/chest/simpleshirt.vrm",
  "/neurohacker/chest/slottedshirt.vrm",
  "/neurohacker/chest/streetware.vrm",
  "/neurohacker/chest/sweater.vrm"
],
eyes: [
  "/neurohacker/eyes/regulareyes.vrm"
],
foot: [
  "/neurohacker/foot/boots.vrm",
  "/neurohacker/foot/dressshoes.vrm",
  "/neurohacker/foot/fantasyboots.vrm",
  "/neurohacker/foot/hikingboots.vrm",
  "/neurohacker/foot/runningshoes.vrm",
  "/neurohacker/foot/shroudedboots.vrm",
  "/neurohacker/foot/simpleshoes.vrm",
  "/neurohacker/foot/sinchboots.vrm",
  "/neurohacker/foot/strapedboots.vrm",
  "/neurohacker/foot/tallboots.vrm"
],
head: [
  "/neurohacker/head/braided.vrm",
  "/neurohacker/head/hair1.vrm",
  "/neurohacker/head/hair2.vrm",
  "/neurohacker/head/hair3.vrm",
  "/neurohacker/head/hair4.vrm",
  "/neurohacker/head/hair5.vrm",
  "/neurohacker/head/hairshort.vrm",
  "/neurohacker/head/short.vrm",
  "/neurohacker/head/straight.vrm",
  "/neurohacker/head/straightdown.vrm"
],
legs: [
  "/neurohacker/legs/cargopants.vrm",
  "/neurohacker/legs/cargoshorts.vrm",
  "/neurohacker/legs/rolleduppants.vrm",
  "/neurohacker/legs/shorts.vrm",
  "/neurohacker/legs/shortsandsweats.vrm",
  "/neurohacker/legs/streetpants.vrm",
  "/neurohacker/legs/suitpants.vrm",
  "/neurohacker/legs/tightjeans.vrm",
  "/neurohacker/legs/workingpants.vrm"
],
outer: [
  "/neurohacker/outer/longjacket.vrm",
  "/neurohacker/outer/robe.vrm"
]
};


export const imagePathsTextureCollections = {   
  _textureCollections: [
    
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2857.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2858.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2859.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2860.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2861.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2862.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2863.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2864.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2865.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2866.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2867.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2868.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2869.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2870.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2871.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2872.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2874.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2875.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2876.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2877.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2878.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2879.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2880.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2881.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2882.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2883.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2884.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2885.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2886.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2887.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2888.png",
    "/character-assets/neurohacker/_textureCollections/eyes/IMG_2889.png",
    "/character-assets/neurohacker/_textureCollections/outfit_1/outfit_1_0.png",
    "/character-assets/neurohacker/_textureCollections/outfit_1/outfit_1_1.png",
    "/character-assets/neurohacker/_textureCollections/outfit_1/outfit_1_2.png",
    "/character-assets/neurohacker/_textureCollections/outfit_1/outfit_1_3.png",
    "/character-assets/neurohacker/_textureCollections/outfit_1/outfit_1_4.png",
    "/character-assets/neurohacker/_textureCollections/outfit_1/outfit_1_5.png",
    "/character-assets/neurohacker/_textureCollections/outfit_1/outfit_1_6.png",
    "/character-assets/neurohacker/_textureCollections/outfit_10/outfit_10_0.png",
    "/character-assets/neurohacker/_textureCollections/outfit_10/outfit_10_1.png",
    "/character-assets/neurohacker/_textureCollections/outfit_10/outfit_10_2.png",
    "/character-assets/neurohacker/_textureCollections/outfit_10/outfit_10_3.png",
    "/character-assets/neurohacker/_textureCollections/outfit_10/outfit_10_4.png",
    "/character-assets/neurohacker/_textureCollections/outfit_10/outfit_10_5.png",
    "/character-assets/neurohacker/_textureCollections/outfit_10/outfit_10_6.png",
    "/character-assets/neurohacker/_textureCollections/outfit_2/outfit_2_0.png",
    "/character-assets/neurohacker/_textureCollections/outfit_2/outfit_2_1.png",
    "/character-assets/neurohacker/_textureCollections/outfit_2/outfit_2_2.png",
    "/character-assets/neurohacker/_textureCollections/outfit_2/outfit_2_3.png",
    "/character-assets/neurohacker/_textureCollections/outfit_2/outfit_2_4.png",
    "/character-assets/neurohacker/_textureCollections/outfit_2/outfit_2_5.png",
    "/character-assets/neurohacker/_textureCollections/outfit_2/outfit_2_6.png",
    "/character-assets/neurohacker/_textureCollections/outfit_3/outfit_3_0.png",
    "/character-assets/neurohacker/_textureCollections/outfit_3/outfit_3_1.png",
    "/character-assets/neurohacker/_textureCollections/outfit_3/outfit_3_2.png",
    "/character-assets/neurohacker/_textureCollections/outfit_3/outfit_3_3.png",
    "/character-assets/neurohacker/_textureCollections/outfit_3/outfit_3_4.png",
    "/character-assets/neurohacker/_textureCollections/outfit_3/outfit_3_5.png",
    "/character-assets/neurohacker/_textureCollections/outfit_3/outfit_3_6.png",
    "/character-assets/neurohacker/_textureCollections/outfit_4/outfit_4_0.png",
    "/character-assets/neurohacker/_textureCollections/outfit_4/outfit_4_1.png",
    "/character-assets/neurohacker/_textureCollections/outfit_4/outfit_4_2.png",
    "/character-assets/neurohacker/_textureCollections/outfit_4/outfit_4_3.png",
    "/character-assets/neurohacker/_textureCollections/outfit_4/outfit_4_4.png",
    "/character-assets/neurohacker/_textureCollections/outfit_4/outfit_4_5.png",
    "/character-assets/neurohacker/_textureCollections/outfit_4/outfit_4_6.png",
    "/character-assets/neurohacker/_textureCollections/outfit_5/outfit_5_0.png",
    "/character-assets/neurohacker/_textureCollections/outfit_5/outfit_5_1.png",
    "/character-assets/neurohacker/_textureCollections/outfit_5/outfit_5_2.png",
    "/character-assets/neurohacker/_textureCollections/outfit_5/outfit_5_3.png",
    "/character-assets/neurohacker/_textureCollections/outfit_5/outfit_5_4.png",
    "/character-assets/neurohacker/_textureCollections/outfit_5/outfit_5_5.png",
    "/character-assets/neurohacker/_textureCollections/outfit_5/outfit_5_6.png",
    "/character-assets/neurohacker/_textureCollections/outfit_6/outfit_6_0.png",
    "/character-assets/neurohacker/_textureCollections/outfit_6/outfit_6_1.png",
    "/character-assets/neurohacker/_textureCollections/outfit_6/outfit_6_2.png",
    "/character-assets/neurohacker/_textureCollections/outfit_6/outfit_6_3.png",
    "/character-assets/neurohacker/_textureCollections/outfit_6/outfit_6_4.png",
    "/character-assets/neurohacker/_textureCollections/outfit_6/outfit_6_5.png",
    "/character-assets/neurohacker/_textureCollections/outfit_6/outfit_6_6.png",
    "/character-assets/neurohacker/_textureCollections/outfit_7/outfit_7_0.png",
    "/character-assets/neurohacker/_textureCollections/outfit_7/outfit_7_1.png",
    "/character-assets/neurohacker/_textureCollections/outfit_7/outfit_7_2.png",
    "/character-assets/neurohacker/_textureCollections/outfit_7/outfit_7_3.png",
    "/character-assets/neurohacker/_textureCollections/outfit_7/outfit_7_4.png",
    "/character-assets/neurohacker/_textureCollections/outfit_7/outfit_7_5.png",
    "/character-assets/neurohacker/_textureCollections/outfit_7/outfit_7_6.png",
    "/character-assets/neurohacker/_textureCollections/outfit_8/outfit_8_0.png",
    "/character-assets/neurohacker/_textureCollections/outfit_8/outfit_8_1.png",
    "/character-assets/neurohacker/_textureCollections/outfit_8/outfit_8_2.png",
    "/character-assets/neurohacker/_textureCollections/outfit_8/outfit_8_3.png",
    "/character-assets/neurohacker/_textureCollections/outfit_8/outfit_8_4.png",
    "/character-assets/neurohacker/_textureCollections/outfit_8/outfit_8_5.png",
    "/character-assets/neurohacker/_textureCollections/outfit_8/outfit_8_6.png",
    "/character-assets/neurohacker/_textureCollections/outfit_9/outfit_9_0.png",
    "/character-assets/neurohacker/_textureCollections/outfit_9/outfit_9_1.png",
    "/character-assets/neurohacker/_textureCollections/outfit_9/outfit_9_2.png",
    "/character-assets/neurohacker/_textureCollections/outfit_9/outfit_9_3.png",
    "/character-assets/neurohacker/_textureCollections/outfit_9/outfit_9_4.png",
    "/character-assets/neurohacker/_textureCollections/outfit_9/outfit_9_5.png",
    "/character-assets/neurohacker/_textureCollections/outfit_9/outfit_9_6.png",
    "/character-assets/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_Face_BaseColor.png",
    "/character-assets/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_Face_BaseColor1.png",
    "/character-assets/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_Face_BaseColor2.png",
    "/character-assets/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_Face_BaseColor3.png",
    "/character-assets/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_Face_BaseColor4.png",
    "/character-assets/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_Face_BaseColor_alt.png",
    "/character-assets/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_skin_BaseColor.png",
    "/character-assets/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_skin_BaseColor1.png",
    "/character-assets/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_skin_BaseColor2.png",
    "/character-assets/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_skin_BaseColor3.png",
    "/character-assets/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_skin_BaseColor4.png",
    "/character-assets/neurohacker/_textureCollections/skin/Anime_Proj_base_NoClothes_skin_BaseColor_alt.png",
    "/character-assets/neurohacker/_textureCollections/skin/ArmSleeves_Original.png",
    "/character-assets/neurohacker/_textureCollections/skin/ArmSleeves_Tone_1.png",
    "/character-assets/neurohacker/_textureCollections/skin/ArmSleeves_Tone_2.png",
    "/character-assets/neurohacker/_textureCollections/skin/ArmSleeves_Tone_3.png",
    "/character-assets/neurohacker/_textureCollections/skin/ArmSleeves_Tone_4.png",
    "/character-assets/neurohacker/_textureCollections/skin/KneeHighs_Original.png",
    "/character-assets/neurohacker/_textureCollections/skin/KneeHighs_Tone_1.png",
    "/character-assets/neurohacker/_textureCollections/skin/KneeHighs_Tone_2.png",
    "/character-assets/neurohacker/_textureCollections/skin/KneeHighs_Tone_3.png",
    "/character-assets/neurohacker/_textureCollections/skin/KneeHighs_Tone_4.png",
    "/character-assets/neurohacker/_textureCollections/skin/original_mouth.png",
    "/character-assets/neurohacker/_textureCollections/skin/skin1_mouth.png",
    "/character-assets/neurohacker/_textureCollections/skin/skin2_mouth.png",
    "/character-assets/neurohacker/_textureCollections/skin/skin3_mouth.png",
    "/character-assets/neurohacker/_textureCollections/skin/skin4_mouth.png",
    "/character-assets/neurohacker/_textureCollections/skin/ThighHighs_Original.png",
    "/character-assets/neurohacker/_textureCollections/skin/ThighHighs_Tone_1.png",
    "/character-assets/neurohacker/_textureCollections/skin/ThighHighs_Tone_2.png",
    "/character-assets/neurohacker/_textureCollections/skin/ThighHighs_Tone_3.png",
    "/character-assets/neurohacker/_textureCollections/skin/ThighHighs_Tone_4.png"
  ]
};